services:
  postgres:
    image: postgres:18
    container_name: mehana-postgres
    environment:
      POSTGRES_USERNAME : ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mehana -U root"]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 30s


  app:
    build: .
    container_name: mehana-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mehana
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      OFFERS_BASE_URL: ${OFFERS_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
