services:
  mysql:
    image: mysql:8.0
    container_name: mehana-mysql
    environment:
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password


  app:
    build: .
    container_name: mehana-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mehana?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      OFFERS_BASE_URL: ${OFFERS_BASE_URL}
    depends_on:
      - mysql
      - orders-api
    restart: on-failure

volumes:
  mysql_data:
